export const NETWORK_OPTIONS = [
  {
    id: 'ethereum-mainnet',
    name: 'Ethereum Mainnet',
    chainId: '1',
    type: 'Mainnet',
    rpcUrl: 'https://rpc.ankr.com/eth',
    symbol: 'ETH',
    explorer: 'https://etherscan.io',
    isCustom: false,
  },
  {
    id: 'polygon-mainnet',
    name: 'Polygon Mainnet',
    chainId: '137',
    type: 'Mainnet',
    rpcUrl: 'https://polygon-rpc.com',
    symbol: 'MATIC',
    explorer: 'https://polygonscan.com',
    isCustom: false,
  },
  {
    id: 'bsc-mainnet',
    name: 'BNB Smart Chain',
    chainId: '56',
    type: 'Mainnet',
    rpcUrl: 'https://bsc-dataseed.binance.org',
    symbol: 'BNB',
    explorer: 'https://bscscan.com',
    isCustom: false,
  },
  {
    id: 'arbitrum-one',
    name: 'Arbitrum One',
    chainId: '42161',
    type: 'Mainnet',
    rpcUrl: 'https://arb1.arbitrum.io/rpc',
    symbol: 'ETH',
    explorer: 'https://arbiscan.io',
    isCustom: false,
  },
  {
    id: 'optimism-mainnet',
    name: 'Optimism',
    chainId: '10',
    type: 'Mainnet',
    rpcUrl: 'https://mainnet.optimism.io',
    symbol: 'ETH',
    explorer: 'https://optimistic.etherscan.io',
    isCustom: false,
  },
  {
    id: 'avalanche-c',
    name: 'Avalanche C-Chain',
    chainId: '43114',
    type: 'Mainnet',
    rpcUrl: 'https://api.avax.network/ext/bc/C/rpc',
    symbol: 'AVAX',
    explorer: 'https://snowtrace.io',
    isCustom: false,
  },
  {
    id: 'base-mainnet',
    name: 'Base',
    chainId: '8453',
    type: 'Mainnet',
    rpcUrl: 'https://mainnet.base.org',
    symbol: 'ETH',
    explorer: 'https://basescan.org',
    isCustom: false,
  },
  {
    id: 'fantom-mainnet',
    name: 'Fantom Opera',
    chainId: '250',
    type: 'Mainnet',
    rpcUrl: 'https://rpc.fantom.network',
    symbol: 'FTM',
    explorer: 'https://ftmscan.com',
    isCustom: false,
  },
  {
    id: 'voltus-mainnet',
    name: 'Voltus Wave',
    chainId: '1234567',
    type: 'Primary',
    rpcUrl: 'http://13.232.1.197:8545',
    symbol: 'VW',
    explorer: null,
    isCustom: false,
  },
];

export const DEFAULT_NETWORK = NETWORK_OPTIONS[0];

export const NETWORK_STORAGE_KEY = 'voltus:selectedNetwork';

export const CUSTOM_NETWORKS_STORAGE_KEY = 'voltus:customNetworks';

